export default function TermsPage() {
  return (
    <main className="page">
      <div className="container">
        <article className="prose">
          <h1>Terms of Service</h1>
          <p className="updated">Last updated: October 2026</p>

          <h2>Acceptance of terms</h2>
          <p>
            By creating an account or using AI Quiz Builder, you agree to these
            terms. If you do not agree, do not use the service.
          </p>

          <h2>Description of service</h2>
          <p>
            AI Quiz Builder is a web application that generates quiz questions on
            topics you specify using a third-party AI model API. Questions are
            graded on the server. Your results are saved to your account.
          </p>

          <h2>Account registration</h2>
          <ul>
            <li>You must provide an accurate email address and a password of at least 6 characters.</li>
            <li>You are responsible for keeping your credentials secure.</li>
            <li>You may not create accounts on behalf of other people without their permission.</li>
            <li>One person, one account. Do not share accounts.</li>
          </ul>

          <h2>Acceptable use</h2>
          <p>You may not use this service to:</p>
          <ul>
            <li>Generate content that is unlawful, threatening, or abusive.</li>
            <li>Attempt to reverse-engineer the grading system or circumvent server-side answer validation.</li>
            <li>Send automated requests at a rate that degrades service for other users.</li>
            <li>Scrape or extract question data in bulk.</li>
          </ul>

          <h2>AI-generated content</h2>
          <p>
            Quiz questions are generated by an AI model and may contain
            inaccuracies. We do not guarantee the factual correctness of
            generated questions or explanations. Do not rely on this service
            as a sole source of factual information.
          </p>

          <h2>Service availability</h2>
          <p>
            We do not guarantee continuous uptime. The service may be
            unavailable for maintenance or due to factors outside our control.
          </p>

          <h2>Termination</h2>
          <p>
            We reserve the right to suspend or delete accounts that violate
            these terms. You may delete your account at any time by contacting
            us.
          </p>

          <h2>Limitation of liability</h2>
          <p>
            This service is provided &ldquo;as is&rdquo; without warranty of any kind.
            We are not liable for damages resulting from your use of the service
            or from inaccuracies in AI-generated content.
          </p>

          <h2>Changes to these terms</h2>
          <p>
            We may update these terms. If changes are material, we will update
            the &ldquo;last updated&rdquo; date. Continued use of the service after changes
            constitutes acceptance.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms can be sent to the email address listed
            on our GitHub repository.
          </p>
        </article>
      </div>
    </main>
  );
}
